use warpfs_core::manifest::Manifest;

const MINIMAL_YAML: &str = r#"
project:
  name: "test-project"
"#;

const COMPLETE_YAML: &str = r#"
version: 2

project:
  name: "my-project"
  description: "Description surfaced to agents"

interfaces:
  fuse:
    enabled: true
    mount_point: /mnt/vfs/project
    allow_other: false
    direct_io: false
    auto_unmount: true
  ninep:
    enabled: false
    listen: "0.0.0.0:5640"
  cli:
    enabled: true
  mcp:
    enabled: true
    transport: stdio
    port: 8766
  golib:
    enabled: false

repos:
  - name: auth-service
    url: git@github.com:org/auth-service.git
    ref: main
    at: /mnt/vfs/workspace/auth-service/
    writable: true
    auto_pull: true
    manifest: .vfs/repo-manifests/auth.yaml
  - name: shared-lib
    url: git@github.com:org/shared-lib.git
    ref: v2.1.0
    at: /mnt/vfs/workspace/shared-lib/
    writable: false
    auto_pull: true

backends:
  s3:
    - bucket: my-project-models
      prefix: prod/
      at: /project/models/
      region: us-east-1
      cache: /tmp/vfs-cache/models/
      ttl: 3600
      writable: false
      lazy_load: true
  remote:
    - url: git@github.com:org/shared-lib.git
      at: /project/vendor/shared-lib/
      ref: main
      cache: /tmp/vfs-cache/shared-lib/
      auto_pull: 3600
  local:
    - path: /data/datasets/
      at: /project/data/
      writable: true

metadata:
  namespaces:
    - feature
    - purpose
    - backend
    - hash
    - origin
    - relations
    - impact
    - complexity
    - risk
    - last_tested
    - last_modified
    - cache_status
    - review_status
  auto:
    hash: true
    last_modified: true
    complexity: true

graph:
  edges: .vfs/graph/edges.jsonl
  blob_index: .vfs/blobs/index.jsonl
  duckdb_cache: .vfs/graph/graph.duckdb
  auto_discover:
    enabled: true
    languages: [go, python, typescript, rust, javascript, java, c, cpp, ruby]
    on_first_read: true
    on_write: true
    on_mount: false
  impact:
    enabled: true
    max_depth: 5
    parallel: true
  cross_repo: true
  max_edges_per_file: 100000
  deduplicate: true
  extensions:
    - name: docs
      pattern: "docs/**/*.md -> src/**/*.go"
      relation: "documented_by"

permissions:
  rules:
    - paths: [".vfs/**"]
      mode: "0444"
    - paths: [".git/**", ".gitignore", ".gitattributes", ".gitmodules"]
      mode: "0444"
    - paths: ["**/go.sum", "**/Cargo.lock", "**/package-lock.json"]
      mode: "0444"
    - paths: ["docs/**", "*.md", "README.md"]
      mode: "0644"
    - paths: ["src/**", "lib/**", "pkg/**", "cmd/**", "internal/**"]
      mode: "0644"
    - paths: ["*.toml", "*.yaml", "*.yml", "*.json"]
      mode: "0644"
      allow_delete: false
  default_mode: "0644"
  backends:
    - name: shared-lib
      mode: "0444"

triggers:
  - name: update-graph
    when: "*"
    on: [write, delete]
    run: parse-and-diff
    async: true
    timeout: 5s
  - name: lint-go
    when: "*.go"
    on: write
    run: "golangci-lint run {{ .FilePath }}"
    async: true
    timeout: 30s
    on_failure: warn
  - name: auto-test
    when: "src/**/*.go"
    on: write
    run: "go test ./{{ .ModulePath }}/..."
    async: true
    timeout: 60s
    debounce: 2s
    on_success:
      set_xattr: "user.vfs.last_tested={{ .Timestamp }}"
  - name: sync-s3
    when: "/project/models/*"
    on: write
    run: upload-to-backend
    async: true
    timeout: 120s

rules:
  - name: stale-files
    description: "Files changed since last test pass"
    query: |
      SELECT path, last_modified, last_tested
      FROM file_registry
      WHERE last_modified > last_tested OR last_tested IS NULL
      ORDER BY last_modified DESC
  - name: untested-critical
    description: "Critical path files with no tests"
    query: |
      SELECT e.to AS file, COUNT(*) AS dependents
      FROM read_json_auto('.vfs/graph/edges.jsonl') e
      WHERE e.rel = 'imports'
      GROUP BY e.to HAVING COUNT(*) > 5
      ORDER BY dependents DESC

plugins:
  - name: sql-scanner
    wasm: .vfs/plugins/sql-scanner.wasm
    hooks:
      - on: file_write
        languages: [go]
        priority: 10
    provides:
      edge_types: [security_audit, compliance_check]
      metadata_namespaces: [security.sql_risk, security.owasp_category]

discovery:
  feature_inference:
    enabled: true
    strategy: directory
    override_file: .vfs/features/tags.yaml
  test_association:
    enabled: true
    patterns:
      - "*_test.go"
      - "test_*.py"
      - "*.test.ts"
      - "*.spec.ts"
  generated_detection:
    enabled: true
    markers:
      - header: "DO NOT EDIT"
      - header: "auto-generated"
      - header: "Code generated by"
      - path: "*.pb.go"
      - path: "*.gen.go"

sandbox:
  enabled: false
  engine: bubblewrap
  isolate_network: true
  isolate_pid: true
  read_only_root: true
  writable_paths:
    - /tmp
    - /workspace

performance:
  cache:
    path: .vfs/cache/
    max_size: 1GB
  fuse:
    attr_timeout: 1.0
    entry_timeout: 1.0
    max_read: 131072
    max_write: 131072
  duckdb:
    threads: 4
    memory_limit: 512MB
  triggers:
    debounce_default: 500ms
    max_concurrent: 8
"#;

#[test]
fn test_parse_minimal() {
    let manifest = Manifest::from_str(MINIMAL_YAML).expect("minimal manifest should parse");
    assert_eq!(manifest.project.name, "test-project");
    assert_eq!(manifest.project.description, "");
}

#[test]
fn test_parse_complete() {
    let manifest = Manifest::from_str(COMPLETE_YAML).expect("complete manifest should parse");

    // Project
    assert_eq!(manifest.project.name, "my-project");
    assert_eq!(manifest.project.description, "Description surfaced to agents");

    // Interfaces
    assert!(manifest.interfaces.fuse.enabled);
    assert_eq!(manifest.interfaces.fuse.mount_point, "/mnt/vfs/project");
    assert!(!manifest.interfaces.ninep.enabled);
    assert_eq!(manifest.interfaces.ninep.listen, "0.0.0.0:5640");
    assert!(manifest.interfaces.mcp.enabled);
    assert_eq!(manifest.interfaces.mcp.transport, "stdio");
    assert_eq!(manifest.interfaces.mcp.port, 8766);

    // Repos
    assert_eq!(manifest.repos.len(), 2);
    assert_eq!(manifest.repos[0].name, "auth-service");
    assert_eq!(manifest.repos[0].git_ref, "main");
    assert!(manifest.repos[0].writable);
    assert_eq!(manifest.repos[0].manifest.as_deref(), Some(".vfs/repo-manifests/auth.yaml"));
    assert_eq!(manifest.repos[1].name, "shared-lib");
    assert_eq!(manifest.repos[1].git_ref, "v2.1.0");
    assert!(!manifest.repos[1].writable);

    // Backends
    assert_eq!(manifest.backends.s3.len(), 1);
    assert_eq!(manifest.backends.s3[0].bucket, "my-project-models");
    assert_eq!(manifest.backends.s3[0].ttl, 3600);
    assert!(!manifest.backends.s3[0].writable);
    assert!(manifest.backends.s3[0].lazy_load);
    assert_eq!(manifest.backends.remote.len(), 1);
    assert_eq!(manifest.backends.remote[0].auto_pull, Some(3600));
    assert_eq!(manifest.backends.local.len(), 1);
    assert!(manifest.backends.local[0].writable);

    // Metadata
    assert_eq!(manifest.metadata.namespaces.len(), 13);
    assert!(manifest.metadata.auto.hash);
    assert!(manifest.metadata.auto.complexity);

    // Graph
    assert_eq!(manifest.graph.edges, ".vfs/graph/edges.jsonl");
    assert!(manifest.graph.auto_discover.enabled);
    assert_eq!(manifest.graph.auto_discover.languages.len(), 9);
    assert_eq!(manifest.graph.impact.max_depth, 5);
    assert!(manifest.graph.cross_repo);
    assert_eq!(manifest.graph.max_edges_per_file, 100000);
    assert_eq!(manifest.graph.extensions.len(), 1);
    assert_eq!(manifest.graph.extensions[0].name, "docs");

    // Permissions
    assert_eq!(manifest.permissions.rules.len(), 6);
    assert_eq!(manifest.permissions.default_mode, "0644");
    assert_eq!(manifest.permissions.backends.len(), 1);
    assert_eq!(
        manifest.permissions.backends[0].name, "shared-lib"
    );

    // Triggers — test both single-string and list `on` forms
    assert_eq!(manifest.triggers.len(), 4);
    assert_eq!(manifest.triggers[0].name, "update-graph");
    assert_eq!(manifest.triggers[0].on, vec!["write", "delete"]);
    assert!(manifest.triggers[0].r#async);
    assert_eq!(manifest.triggers[1].name, "lint-go");
    assert_eq!(manifest.triggers[1].on, vec!["write"]); // single-string form
    assert_eq!(manifest.triggers[1].on_failure.as_deref(), Some("warn"));
    assert_eq!(manifest.triggers[2].name, "auto-test");
    assert_eq!(
        manifest.triggers[2].on_success.as_ref().unwrap().set_xattr.as_deref(),
        Some("user.vfs.last_tested={{ .Timestamp }}")
    );

    // Rules
    assert_eq!(manifest.rules.len(), 2);
    assert_eq!(manifest.rules[0].name, "stale-files");
    assert!(manifest.rules[0].query.contains("file_registry"));

    // Plugins
    assert_eq!(manifest.plugins.len(), 1);
    assert_eq!(manifest.plugins[0].hooks[0].priority, 10);
    assert_eq!(manifest.plugins[0].provides.as_ref().unwrap().edge_types.len(), 2);

    // Discovery
    assert!(manifest.discovery.feature_inference.enabled);
    assert_eq!(manifest.discovery.feature_inference.strategy, "directory");
    assert_eq!(manifest.discovery.test_association.patterns.len(), 4);
    assert_eq!(manifest.discovery.generated_detection.markers.len(), 5);
    assert_eq!(
        manifest.discovery.generated_detection.markers[0].header.as_deref(),
        Some("DO NOT EDIT")
    );
    assert_eq!(
        manifest.discovery.generated_detection.markers[3].path.as_deref(),
        Some("*.pb.go")
    );

    // Sandbox
    assert!(!manifest.sandbox.enabled);
    assert_eq!(manifest.sandbox.engine.as_deref(), Some("bubblewrap"));
    assert!(manifest.sandbox.isolate_network);
    assert_eq!(manifest.sandbox.writable_paths.len(), 2);

    // Performance
    assert_eq!(manifest.performance.cache.max_size, "1GB");
    assert_eq!(manifest.performance.fuse.attr_timeout, 1.0);
    assert_eq!(manifest.performance.fuse.max_read, 131072);
    assert_eq!(manifest.performance.duckdb.threads, 4);
    assert_eq!(manifest.performance.triggers.max_concurrent, 8);
}

#[test]
fn test_unknown_keys_rejected() {
    let yaml = r#"
project:
  name: "test"
completely_unknown_key: "should fail"
"#;
    let result = Manifest::from_str(yaml);
    assert!(result.is_err(), "unknown top-level key must be rejected");
}

#[test]
fn test_unknown_nested_key_rejected() {
    let yaml = r#"
project:
  name: "test"
interfaces:
  fuse:
    bogus_field: true
"#;
    let result = Manifest::from_str(yaml);
    assert!(result.is_err(), "unknown nested key must be rejected");
}

#[test]
fn test_defaults_applied() {
    let manifest = Manifest::from_str(MINIMAL_YAML).expect("minimal should parse");

    // Version defaults to 2
    assert_eq!(manifest.version, 2);

    // Fuse defaults
    assert!(manifest.interfaces.fuse.enabled);
    assert_eq!(manifest.interfaces.fuse.mount_point, "/mnt/vfs/project");
    assert!(!manifest.interfaces.fuse.allow_other);
    assert!(!manifest.interfaces.fuse.direct_io);
    assert!(manifest.interfaces.fuse.auto_unmount);

    // 9P defaults
    assert!(!manifest.interfaces.ninep.enabled);
    assert_eq!(manifest.interfaces.ninep.listen, "0.0.0.0:5640");

    // CLI defaults
    assert!(manifest.interfaces.cli.enabled);

    // MCP defaults
    assert!(manifest.interfaces.mcp.enabled);
    assert_eq!(manifest.interfaces.mcp.transport, "stdio");
    assert_eq!(manifest.interfaces.mcp.port, 8766);

    // GoLib defaults
    assert!(!manifest.interfaces.golib.enabled);

    // Metadata defaults
    assert!(manifest.metadata.auto.hash);
    assert!(manifest.metadata.auto.last_modified);
    assert!(manifest.metadata.auto.complexity);

    // Graph defaults
    assert!(manifest.graph.auto_discover.enabled);
    assert!(manifest.graph.impact.enabled);
    assert_eq!(manifest.graph.impact.max_depth, 5);
    assert!(manifest.graph.cross_repo);
    assert_eq!(manifest.graph.max_edges_per_file, 100000);
    assert!(manifest.graph.deduplicate);

    // Permissions defaults
    assert_eq!(manifest.permissions.default_mode, "0644");

    // Sandbox defaults
    assert!(!manifest.sandbox.enabled);
    assert!(manifest.sandbox.engine.is_none());

    // Performance defaults
    assert_eq!(manifest.performance.cache.path, ".vfs/cache/");
    assert_eq!(manifest.performance.cache.max_size, "1GB");
    assert_eq!(manifest.performance.fuse.attr_timeout, 1.0);
    assert_eq!(manifest.performance.fuse.entry_timeout, 1.0);
    assert_eq!(manifest.performance.fuse.max_read, 131072);
    assert_eq!(manifest.performance.fuse.max_write, 131072);
    assert_eq!(manifest.performance.duckdb.threads, 4);
    assert_eq!(manifest.performance.duckdb.memory_limit, "512MB");
    assert_eq!(manifest.performance.triggers.debounce_default, "500ms");
    assert_eq!(manifest.performance.triggers.max_concurrent, 8);

    // Discovery defaults
    assert!(manifest.discovery.feature_inference.enabled);
    assert_eq!(manifest.discovery.feature_inference.strategy, "directory");
    assert!(manifest.discovery.test_association.enabled);
    assert!(!manifest.discovery.test_association.patterns.is_empty());
    assert!(manifest.discovery.generated_detection.enabled);

    // Empty collections
    assert!(manifest.repos.is_empty());
    assert!(manifest.triggers.is_empty());
    assert!(manifest.rules.is_empty());
    assert!(manifest.plugins.is_empty());
}

#[test]
fn test_version_defaults_to_2() {
    let manifest = Manifest::from_str(MINIMAL_YAML).expect("should parse");
    assert_eq!(manifest.version, 2);
}

#[test]
fn test_version_explicit() {
    let yaml = r#"
version: 3
project:
  name: "v3-project"
"#;
    let manifest = Manifest::from_str(yaml).expect("should parse");
    assert_eq!(manifest.version, 3);
}

#[test]
fn test_from_file() {
    let dir = tempfile::tempdir().expect("failed to create temp dir");
    let path = dir.path().join("manifest.yaml");
    std::fs::write(&path, MINIMAL_YAML).expect("failed to write file");

    let path_str = path.to_str().expect("path is valid utf-8");
    let manifest = Manifest::from_file(path_str).expect("should parse from file");
    assert_eq!(manifest.project.name, "test-project");
    assert_eq!(manifest.version, 2);
}

#[test]
fn test_config_from_file() {
    let dir = tempfile::tempdir().expect("failed to create temp dir");
    let path = dir.path().join("manifest.yaml");
    std::fs::write(&path, COMPLETE_YAML).expect("failed to write file");

    let path_str = path.to_str().expect("path is valid utf-8");
    let config = warpfs_core::config::Config::from_file(path_str)
        .expect("config should parse from file");
    assert_eq!(config.manifest.project.name, "my-project");
}

#[test]
fn test_generated_marker_union() {
    let yaml = r#"
project:
  name: "marker-test"
discovery:
  generated_detection:
    enabled: true
    markers:
      - header: "DO NOT EDIT"
      - path: "*.gen.go"
      - header: "auto-generated"
"#;
    let manifest = Manifest::from_str(yaml).expect("should parse");
    let markers = &manifest.discovery.generated_detection.markers;
    assert_eq!(markers.len(), 3);
    assert!(markers[0].header.is_some());
    assert!(markers[0].path.is_none());
    assert!(markers[1].header.is_none());
    assert!(markers[1].path.is_some());
    assert!(markers[2].header.is_some());
}
